In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np 
%matplotlib inline

In [ ]:

df=pd.read_csv('breast-cancer.data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [ ]:
# Separating Input columns and the Output column
data = df.values
X = data[:,2:-1]
Y = data[:,1]
print(X,Y)

In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=10)
print(X_test, y_test)

In [ ]:
from sklearn.model_selection import KFold
fold = KFold(n_splits=5)
fold

In [ ]:
fold.split('breast_cancer.data.csv')
print(X_train, X_test)
print(y_train, y_test)

In [ ]:
for train_index, test_index in fold.split('breast_cancer.data.csv'):
  print(train_index, test_index )


In [ ]:
# MODEL 1 Support Vector Machine (SVM)

from sklearn.svm import SVC
model_svc = SVC()
model_svc.fit(X_train, y_train)

In [ ]:

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
prediction1 = model_svc.predict(X_test)
from sklearn.metrics import accuracy_score , confusion_matrix , recall_score, precision_score,precision_recall_curve, f1_score, precision_recall_fscore_support
print(accuracy_score(y_test, prediction1)*100)
print(confusion_matrix(y_test,prediction1))
pd.crosstab(y_test,prediction1)
print(classification_report(y_test,prediction1))


93.56725146198829
[[109   3]
 [  8  51]]
              precision    recall  f1-score   support

           B       0.93      0.97      0.95       112
           M       0.94      0.86      0.90        59

    accuracy                           0.94       171
   macro avg       0.94      0.92      0.93       171
weighted avg       0.94      0.94      0.93       171



In [ ]:
# MODEL 2 Logistic Regression

from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(X_train, y_train)

In [ ]:
prediction2 = model_LR.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction2)*100)
print(confusion_matrix(y_test,prediction2))
pd.crosstab(y_test,prediction2)

95.32163742690058
[[106   6]
 [  2  57]]


col_0    B   M
row_0         
B      106   6
M        2  57

In [ ]:
# MODEL 3 Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier()
model_DT.fit(X_train, y_train)

In [ ]:
prediction3 = model_DT.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction3)*100)
print(confusion_matrix(y_test,prediction3))
pd.crosstab(y_test,prediction2)

91.22807017543859
[[101  11]
 [  4  55]]


col_0    B   M
row_0         
B      106   6
M        2  57

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_knn =  KNeighborsClassifier()
model_knn.fit(X_train, y_train)

In [ ]:
prediction4 = model_knn.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction4)*100)
print(confusion_matrix(y_test,prediction4))
pd.crosstab(y_test,prediction2)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_RF =  RandomForestClassifier()
model_RF.fit(X_train, y_train)

In [ ]:
prediction5 = model_RF.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction5)*100)
print(accuracy_score(y_test, prediction5)*100)
print(confusion_matrix(y_test,prediction5))
pd.crosstab(y_test,prediction2)

98.24561403508771
98.24561403508771
[[109   3]
 [  0  59]]


col_0    B   M
row_0         
B      106   6
M        2  57