In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import numpy as np 
%matplotlib inline

In [ ]:

df=pd.read_csv('breast-cancer.data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [ ]:
# Separating Input columns and the Output column
data = df.values
X = data[:,2:-1]
Y = data[:,1]
print(X,Y)

[[17.99 10.38 122.8 ... 0.7119 0.2654 0.4601]
 [20.57 17.77 132.9 ... 0.2416 0.186 0.275]
 [19.69 21.25 130.0 ... 0.4504 0.243 0.3613]
 ...
 [16.6 28.08 108.3 ... 0.3403 0.1418 0.2218]
 [20.6 29.33 140.1 ... 0.9387 0.265 0.4087]
 [7.76 24.54 47.92 ... 0.0 0.0 0.2871]] ['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 

In [ ]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=10)
print(X_test, y_test)

[[15.46 11.89 102.5 ... 0.583 0.1827 0.3216]
 [9.333 21.94 59.01 ... 0.07993 0.02564 0.2435]
 [13.69 16.07 87.84 ... 0.1346 0.06987 0.3323]
 ...
 [11.08 14.71 70.21 ... 0.03938 0.04306 0.1902]
 [13.64 15.6 87.38 ... 0.1533 0.09222 0.253]
 [12.87 19.54 82.67 ... 0.07127 0.06384 0.3313]] ['M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B'
 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'M' 'M' 'B' 'B' 'B' 'M' 'B'
 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B'
 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'M'
 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B'
 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B'
 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B']


In [ ]:
from sklearn.model_selection import KFold
fold = KFold(n_splits=5)
fold

KFold(n_splits=5, random_state=None, shuffle=False)

In [ ]:
fold.split('breast_cancer.data.csv')
print(X_train, X_test)
print(y_train, y_test)

[[12.4 17.68 81.47 ... 0.2403 0.0737 0.2556]
 [19.55 23.21 128.9 ... 0.3829 0.1825 0.2576]
 [13.05 13.84 82.71 ... 0.01824 0.03532 0.2107]
 ...
 [12.34 12.27 78.94 ... 0.1791 0.107 0.311]
 [13.85 17.21 88.44 ... 0.08115 0.05104 0.2364]
 [20.73 31.12 135.7 ... 0.3442 0.1659 0.2868]] [[15.46 11.89 102.5 ... 0.583 0.1827 0.3216]
 [9.333 21.94 59.01 ... 0.07993 0.02564 0.2435]
 [13.69 16.07 87.84 ... 0.1346 0.06987 0.3323]
 ...
 [11.08 14.71 70.21 ... 0.03938 0.04306 0.1902]
 [13.64 15.6 87.38 ... 0.1533 0.09222 0.253]
 [12.87 19.54 82.67 ... 0.07127 0.06384 0.3313]]
['B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'M'
 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M'
 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B'
 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B'
 'B' 'M' 'M' 'M' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B'
 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'M' 'B' 

In [ ]:
for train_index, test_index in fold.split('breast_cancer.data.csv'):
  print(train_index, test_index )


[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] [0 1 2]
[ 0  1  2  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21] [3 4 5]
[ 0  1  2  3  4  5  8  9 10 11 12 13 14 15 16 17 18 19 20 21] [6 7]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 18 19 20 21] [8 9]
[ 0  1  2  3  4  5  6  7  8  9 12 13 14 15 16 17 18 19 20 21] [10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 14 15 16 17 18 19 20 21] [12 13]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 16 17 18 19 20 21] [14 15]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 18 19 20 21] [16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 20 21] [18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [20 21]


'from posixpath import split\nfor train_index, test_index in range fold.split(breast_cancer.data.csv):\n  print(train_index, test_index)'

In [ ]:
# MODEL 1 Support Vector Machine (SVM)

from sklearn.svm import SVC
model_svc = SVC()
model_svc.fit(X_train, y_train)

SVC()

In [ ]:

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
prediction1 = model_svc.predict(X_test)
from sklearn.metrics import accuracy_score , confusion_matrix , recall_score, precision_score,precision_recall_curve, f1_score, precision_recall_fscore_support
print(accuracy_score(y_test, prediction1)*100)
print(confusion_matrix(y_test,prediction1))
pd.crosstab(y_test,prediction1)
print(classification_report(y_test,prediction1))


93.56725146198829
[[109   3]
 [  8  51]]
              precision    recall  f1-score   support

           B       0.93      0.97      0.95       112
           M       0.94      0.86      0.90        59

    accuracy                           0.94       171
   macro avg       0.94      0.92      0.93       171
weighted avg       0.94      0.94      0.93       171



In [ ]:
# MODEL 2 Logistic Regression

from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(X_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
prediction2 = model_LR.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction2)*100)
print(confusion_matrix(y_test,prediction2))
pd.crosstab(y_test,prediction2)

95.32163742690058
[[106   6]
 [  2  57]]


col_0    B   M
row_0         
B      106   6
M        2  57

In [ ]:
# MODEL 3 Decision Tree Classifier

from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier()
model_DT.fit(X_train, y_train)

DecisionTreeClassifier()

In [ ]:
prediction3 = model_DT.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction3)*100)
print(confusion_matrix(y_test,prediction3))
pd.crosstab(y_test,prediction2)

91.22807017543859
[[101  11]
 [  4  55]]


col_0    B   M
row_0         
B      106   6
M        2  57

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model_knn =  KNeighborsClassifier()
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
prediction4 = model_knn.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction4)*100)
print(accuracy_score(y_test, prediction4)*100)
print(confusion_matrix(y_test,prediction4))
pd.crosstab(y_test,prediction2)

94.15204678362574
94.15204678362574
[[107   5]
 [  5  54]]


col_0    B   M
row_0         
B      106   6
M        2  57

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model_RF =  RandomForestClassifier()
model_RF.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
prediction5 = model_RF.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, prediction5)*100)
print(accuracy_score(y_test, prediction5)*100)
print(confusion_matrix(y_test,prediction5))
pd.crosstab(y_test,prediction2)

98.24561403508771
98.24561403508771
[[109   3]
 [  0  59]]


col_0    B   M
row_0         
B      106   6
M        2  57